/// \file icaocodes.cpp
/// \brief icao addresa definitions per country




#include "icaocodes.h"


ICAOAddressPrefix icao_codes[]=
{
{ICAO_AFGHANISTAN,              "Afghanistan",            12,              0x700000},
{ICAO_ALBANIA,                  "Albania",                14,              0x501000},
{ICAO_ALGERIA,                  "Algeria",                9,               0x0a0000},
{ICAO_ANGOLA,                   "Angola",                 12,              0x090000},
{ICAO_ANTIGUA_BARBUDA,          "Antigua and Barbuda",    14,              0x0ca000},
{ICAO_ARGENTINA,                "Argentina",              6,               0xe00000},
{ICAO_ARMENIA,                  "Armenia",                14,              0x600000},
{ICAO_AUSTRALIA,                "Australia",              6,               0x7c0000},
{ICAO_AUSTRIA,                  "Austria",                9,               0x440000},
{ICAO_AZERBAIJAN,               "Azerbaijan",             14,              0x600800},
{ICAO_BAHAMAS,                  "Bahamas",                12,              0x0a8000},
{ICAO_BAHRAIN,                  "Bahrain",                12,              0x894000},
{ICAO_BANGLADESH,               "Bangladesh",             12,              0x702000},
{ICAO_BARBADOS,                 "Barbados",               14,              0x0aa000},
{ICAO_BELARUS,                  "Belarus",                14,              0x510000},
{ICAO_BELGIUM,                  "Belgium",                9,               0x448000},
{ICAO_BELIZE,                   "Belize",                 14,              0x0ab000},
{ICAO_BENIN,                    "Benin",                  14,              0x094000},
{ICAO_BHUTAN,                   "Bhutan",                 14,              0x680000},
{ICAO_BOLIVIA,                  "Bolivia",                12,              0xe94000},
{ICAO_BOSNIA_HERZEGOVINA,       "Bosnia and Herzegovina", 14,              0x513000},
{ICAO_BOTSWANA,                 "Botswana",               14,              0x030000},
{ICAO_BRAZIL,                   "Brazil",                 6,               0xe40000},
{ICAO_BRUNEI_DARUSSALAM,        "Brunei Darussalam",      14,              0x895000},
{ICAO_BULGARIA,                 "Bulgaria",               9,               0x450000},
{ICAO_BURKINA_FASO,             "Burkina Faso",           12,              0x09c000},
{ICAO_BURUNDI,                  "Burundi",                12,              0x032000},
{ICAO_CAMBODIA,                 "Cambodia",               12,              0x70e000},
{ICAO_CAMEROON,                 "Cameroon",               12,              0x034000},
{ICAO_CANADA,                   "Canada",                 6,               0xc00000},
{ICAO_CAPE_VERDE,               "Cape Verde",             14,              0x096000},
{ICAO_CENTRAL_AFRICAN_REPUBLIC, "Central African Republic",12,             0x06c000},
{ICAO_CHAD,                     "Chad",                    12,             0x084000},
{ICAO_CHILE,                    "Chile",                   12,             0xe80000},
{ICAO_CHINA,                    "China",                   6,              0x780000},
{ICAO_COLOMBIA,                 "Colombia",                12,             0x0ac000},
{ICAO_COMOROS,                  "Comoros",                 14,             0x035000},
{ICAO_CONGO,                    "Congo",                   12,             0x036000},
{ICAO_COOK_ISLANDS,             "Cook Islands",            14,             0x901000},
{ICAO_COSTA_RICA,               "Costa Rica",              12,             0x0ae000},
{ICAO_COTE_D_IVOIRE,            "Côte d Ivoire",           12,             0x038000},
{ICAO_CROATIA,                  "Croatia",                 14,             0x501c00},
{ICAO_CUBA,                     "Cuba",                    12,             0x0b0000},
{ICAO_CYPRUS,                   "Cyprus",                  14,             0x4c8000},
{ICAO_CZECH_REPUBLIC,           "Czech Republic",          9,              0x498000},
{ICAO_DPR_KOREA,              "Democratic People's Republic of Korea", 9, 0x720000},
{ICAO_CONGO,                    "Democratic Republic of the Congo",  12,   0x08c000},
{ICAO_DENMARK,                  "Denmark",                            9,   0x458000},
{ICAO_DJIBOUTI,                 "Djibouti",                           14,  0x098000},
{ICAO_DOMINICAN_REPUBLIC,       "Dominican Republic",               12,    0x0c4000},
{ICAO_ECUADOR,                  "Ecuador",                          12,    0xe84000},
{ICAO_EGYPT,                    "Egypt",                            9,     0x010000},
{ICAO_EL_SALVADOR,              "El Salvador",                      12,    0x0b2000},
{ICAO_GUINEA,                   "Equatorial Guinea",                12,    0x042000},
{ICAO_ERITREA,                  "Eritrea",                          14,    0x202000},
{ICAO_ESTONIA,                  "Estonia",                          14,    0x511000},
{ICAO_ETHIOPIA,                 "Ethiopia",                         12,    0x040000},
{ICAO_FIJI,                     "Fiji",                             12,    0xc88000},
{ICAO_FINLAND,                  "Finland",                          9,     0x460000},
{ICAO_FRANCE,                   "France",                           6,     0x380000},
{ICAO_GABON,                    "Gabon",                           12,     0x03e000},
{ICAO_GAMBIA,                   "Gambia",                          12,     0x09a000},
{ICAO_GEORGIA,                  "Georgia",                         14,     0x514000},
{ICAO_GERMANY,                  "Germany",                         6,      0x3c0000},
{ICAO_GHANA,                    "Ghana",                           12,     0x044000},
{ICAO_GREECE,                   "Greece",                          9,      0x468000},
{ICAO_GRENADA,                  "Grenada",                         14,     0x0cc000},
{ICAO_GUATEMALA,                "Guatemala",                       12,     0x0b4000},
{ICAO_GUINEA,                   "Guinea",                           12,    0x046000},
{ICAO_GUINEA_BISSAU,            "Guinea-Bissau",                   14,     0x048000},
{ICAO_GUYANA,                   "Guyana",                          12,     0x0b6000},
{ICAO_HAITI,                    "Haiti",                           12,     0x0b8000},
{ICAO_HONDURAS,                 "Honduras",                        12,     0x0ba000},
{ICAO_HUNGARY,                  "Hungary",                         9,      0x470000},
{ICAO_ICELAND,                  "Iceland",                         12,     0x4cc000},
{ICAO_INDIA,                    "India",                           6,      0x800000},
{ICAO_INDONESIA,                "Indonesia",                       9,      0x8a0000},
{ICAO_IRAN,                     "Iran, Islamic Republic of",       9,      0x730000},
{ICAO_IRAQ,                     "Iraq",                            9,      0x728000},
{ICAO_IRELAND,                  "Ireland",                         12,     0x4ca000},
{ICAO_ISRAEL,                   "Israel",                          9,      0x738000},
{ICAO_ITALY,                    "Italy",                           6,      0x300000},
{ICAO_JAMAICA,                  "Jamaica",                         12,     0x0be000},
{ICAO_JAPAN,                    "Japan",                           6,      0x840000},
{ICAO_JORDAN,                   "Jordan",                          9,      0x740000},
{ICAO_KAZAKHSTAN,               "Kazakhstan",                      14,     0x683000},
{ICAO_KENYA,                    "Kenya",                           12,     0x04c000},
{ICAO_KIRIBATI,                 "Kiribati",                        14,     0xc8e000},
{ICAO_KUWAIT,                   "Kuwait",                          12,     0x706000},
{ICAO_KYRGYZSTAN,               "Kyrgyzstan",                      14,     0x601000},
{ICAO_LAO_PDR,                     "Lao People's Democratic Republic",12,  0x708000},
{ICAO_LATVIA,                   "Latvia",                          14,     0x502c00},
{ICAO_LEBANON,                  "Lebanon",                         9,      0x748000},
{ICAO_LESOTHO,                  "Lesotho",                         14,     0x04a000},
{ICAO_LIBERIA,                  "Liberia",                         12,     0x050000},
{ICAO_LIBYA,                    "Libyan Arab Jamahiriya",          9,      0x018000},
{ICAO_LITHUANIA,                "Lithuania",                       14,     0x503c00},
{ICAO_LUXEMBOURG,               "Luxembourg",                      14,     0x4d0000},
{ICAO_MADAGASCAR,               "Madagascar",                      12,     0x054000},
{ICAO_MALAWI,                   "Malawi",                          12,     0x058000},
{ICAO_MALAYSIA,                 "Malaysia",                        9,      0x750000},
{ICAO_MALDIVES,                 "Maldives",                        14,     0x05a000},
{ICAO_MALI,                     "Mali",                            12,     0x05c000},
{ICAO_MALTA,                    "Malta",                           14,     0x4d2000},
{ICAO_MARSHALL_ISLANDS,         "Marshall Islands",                14,     0x900000},
{ICAO_MAURITANIA,               "Mauritania",                      14,     0x05e000},
{ICAO_MAURITIUS,                "Mauritius",                       14,     0x060000},
{ICAO_MEXICO,                   "Mexico",                          9,      0x0d0000},
{ICAO_MICRONESIA,               "Micronesia, Federated States of", 14,     0x681000},
{ICAO_MONACO,                   "Monaco",                          14,     0x4d4000},
{ICAO_MONGOLIA,                 "Mongolia",                        14,     0x682000},
{ICAO_MOROCCO,                  "Morocco",                         9,      0x020000},
{ICAO_MOZAMBIQUE,               "Mozambique",                      12,     0x006000},
{ICAO_MYANMAR,                  "Myanmar",                         12,     0x704000},
{ICAO_NAMIBIA,                  "Namibia",                         14,     0x201000},
{ICAO_NAURU,                    "Nauru",                           14,     0xc8a000},
{ICAO_NEPAL,                    "Nepal",                           12,     0x70a000},
{ICAO_NETHERLANDS,              "Netherlands, Kingdom of the",     9,      0x480000},
{ICAO_NEW_ZEALAND,              "New Zealand",                     9,      0xc80000},
{ICAO_NICARAGUA,                "Nicaragua",                      12,      0x0c0000},
{ICAO_NIGER,                    "Niger",                          12,      0x062000},
{ICAO_NIGERIA,                  "Nigeria",                        12,      0x064000},
{ICAO_NORWAY,                   "Norway",                         9,       0x478000},
{ICAO_OMAN,                     "Oman",                          14,       0x70c000},
{ICAO_PAKISTAN,                 "Pakistan",                      9,        0x760000},
{ICAO_PALAU,                    "Palau",                         14,       0x684000},
{ICAO_PANAMA,                   "Panama",                        12,       0x0c2000},
{ICAO_PAPUA_NEW_GUINEA,         "Papua New Guinea",              12,       0x898000},
{ICAO_PARAGUAY,                 "Paraguay",                      12,       0xe88000},
{ICAO_PERU,                     "Peru",                          12,       0xe8c000},
{ICAO_PHILIPPINES,              "Philippines",                   9,        0x758000},
{ICAO_POLAND,                   "Poland",                        9,        0x488000},
{ICAO_PORTUGAL,                 "Portugal",                      9,        0x490000},
{ICAO_QATAR,                    "Qatar",                         14,       0x06a000},
{ICAO_SOUTH_KOREA,              "Republic of Korea",             9,        0x718000},
{ICAO_MOLDOVA,                  "Republic of Moldova",           14,       0x504c00},
{ICAO_ROMANIA,                  "Romania",                       9,        0x4a0000},
{ICAO_RUSSIA,                   "Russian Federation",            4,        0x100000},
{ICAO_RWANDA,                   "Rwanda",                        12,       0x06e000},
{ICAO_SAINT_LUCIA,              "Saint Lucia",                    14,      0xc8c000},
{ICAO_SAINT_VINCENT_GRENADINES, "Saint Vincent and the Grenadines",14,     0x0bc000},
{ICAO_SAMOA,                    "Samoa",                           14,     0x902000},
{ICAO_SAN_MARINO,               "San Marino",                      14,     0x500000},
{ICAO_SAO_TOME_PRINCIPE,        "Sao Tome and Principe",           14,     0x09e000},
{ICAO_SAUDI_ARABIA,             "Saudi Arabia",                    9,      0x710000},
{ICAO_SENEGAL,                  "Senegal",                         12,     0x070000},
{ICAO_SEYCHELLES,               "Seychelles",                      14,     0x074000},
{ICAO_SIERRA_LEONE,             "Sierra Leone",                    14,     0x076000},
{ICAO_SINGAPORE,                "Singapore",                       9,      0x768000},
{ICAO_SLOVAKIA,                 "Slovakia",                        14,     0x505c00},
{ICAO_SLOVENIA,                 "Slovenia",                         14,    0x506c00},
{ICAO_SOLOMON_ISLANDS,          "Solomon Islands",                  14,    0x897000},
{ICAO_SOMALIA,                  "Somalia",                         12,     0x078000},
{ICAO_SOUTH_AFRICA,             "South Africa",                    9,      0x008000},
{ICAO_SPAIN,                    "Spain",                           6,      0x340000},
{ICAO_SRI_LANKA,                "Sri Lanka",                       9,      0x770000},
{ICAO_SUDAN,                    "Sudan",                           12,     0x07c000},
{ICAO_SURINAME,                 "Suriname",                        12,     0x0c8000},
{ICAO_SWAZILAND,                "Swaziland",                       14,     0x07a000},
{ICAO_SWEDEN,                   "Sweden",                          9,      0x4a8000},
{ICAO_SWITZERLAND,              "Switzerland",                     9,      0x4b0000},
{ICAO_SYRIA,                    "Syrian Arab Republic",            9,      0x778000},
{ICAO_TAJIKISTAN,               "Tajikistan",                      14,     0x515000},
{ICAO_THAILAND,                 "Thailand",                        9,      0x880000},
{ICAO_MACEDONIA,                "Republic of Macedonia",           14,     0x512000},
{ICAO_TOGO,                     "Togo",                            12,     0x088000},
{ICAO_TONGA,                    "Tonga",                           14,     0xc8d000},
{ICAO_TRINIDAD_TOBAGO,          "Trinidad and Tobago",             12,     0x0c6000},
{ICAO_TUNISIA,                  "Tunisia",                         9,      0x028000},
{ICAO_TURKEY,                   "Turkey",                          9,      0x4b8000},
{ICAO_TURKMENISTAN,             "Turkmenistan",                    14,     0x601800},
{ICAO_UGANDA,                   "Uganda",                          12,     0x068000},
{ICAO_UKRAINE,                  "Ukraine",                         9,      0x508000},
{ICAO_UAE,                      "United Arab Emirates",            12,     0x896000},
{ICAO_UNITED_KINGDOM,           "United Kingdom",                  6,      0x400000},
{ICAO_TANZANIA,                 "United Republic of Tanzania",     12,     0x080000},
{ICAO_UNITED_STATES,            "United States",                   4,      0xa00000},
{ICAO_URUGUAY,                  "Uruguay",                         12,     0xe90000},
{ICAO_UZBEKISTAN,               "Uzbekistan",                      14,     0x507c00},
{ICAO_VANUATU,                  "Vanuatu",                         14,     0xc90000},
{ICAO_VENEZUELA,                "Venezuela",                       9,      0x0d8000},
{ICAO_VIET_NAM,                 "Viet Nam",                        9,      0x888000},
{ICAO_YEMEN,                    "Yemen",                           12,     0x890000},
{ICAO_YUGOSLAVIA,               "Yugoslavia",                      9,      0x4c0000},
{ICAO_ZAMBIA,                   "Zambia",                          12,     0x08a000},
{ICAO_ZIMBABWE,                 "Zimbabwe",                        14,     0x004000},
{ICAO_COUNTRY_CODE_END,         "",                                0,      0x000000},
{ICAO_COUNTRY_CODE_ERROR,       "ICAO Country Error",              0,      0x000000},

    
    };
