/// \file icaocodes.h
/// \brief icao address structures


#ifndef __icaocodes_h
#define __icaocodes_h

//Values match the indexes in the icao_codes array
enum ICAO_Country
{
ICAO_AFGHANISTAN, ICAO_ALBANIA, ICAO_ALGERIA, ICAO_ANGOLA, ICAO_ANTIGUA_BARBUDA,
ICAO_ARGENTINA, ICAO_ARMENIA, ICAO_AUSTRALIA, ICAO_AUSTRIA, ICAO_AZERBAIJAN,
ICAO_BAHAMAS, ICAO_BAHRAIN, ICAO_BANGLADESH, ICAO_BARBADOS, ICAO_BELARUS,
ICAO_BELGIUM, ICAO_BELIZE, ICAO_BENIN, ICAO_BHUTAN, ICAO_BOLIVIA,
ICAO_BOSNIA_HERZEGOVINA, ICAO_BOTSWANA, ICAO_BRAZIL, ICAO_BRUNEI_DARUSSALAM,
ICAO_BULGARIA, ICAO_BURKINA_FASO, ICAO_BURUNDI, ICAO_CAMBODIA, ICAO_CAMEROON,
ICAO_CANADA, ICAO_CAPE_VERDE, ICAO_CENTRAL_AFRICAN_REPUBLIC, ICAO_CHAD,
ICAO_CHILE, ICAO_CHINA, ICAO_COLOMBIA, ICAO_COMOROS, ICAO_CONGO,
ICAO_COOK_ISLANDS, ICAO_COSTA_RICA, ICAO_COTE_D_IVOIRE, ICAO_CROATIA,
ICAO_CUBA, ICAO_CYPRUS, ICAO_CZECH_REPUBLIC, ICAO_DPR_KOREA, ICAO_DPR_CONGO,
ICAO_DENMARK, ICAO_DJIBOUTI, ICAO_DOMINICAN_REPUBLIC, ICAO_ECUADOR, ICAO_EGYPT,
ICAO_EL_SALVADOR, ICAO_EQUATORIAL_GUINEA, ICAO_ERITREA, ICAO_ESTONIA,
ICAO_ETHIOPIA, ICAO_FIJI, ICAO_FINLAND, ICAO_FRANCE, ICAO_GABON, ICAO_GAMBIA,
ICAO_GEORGIA, ICAO_GERMANY, ICAO_GHANA, ICAO_GREECE, ICAO_GRENADA,
ICAO_GUATEMALA, ICAO_GUINEA, ICAO_GUINEA_BISSAU, ICAO_GUYANA, ICAO_HAITI,
ICAO_HONDURAS, ICAO_HUNGARY, ICAO_ICELAND, ICAO_INDIA, ICAO_INDONESIA,
ICAO_IRAN, ICAO_IRAQ, ICAO_IRELAND, ICAO_ISRAEL, ICAO_ITALY, ICAO_JAMAICA,
ICAO_JAPAN, ICAO_JORDAN, ICAO_KAZAKHSTAN, ICAO_KENYA, ICAO_KIRIBATI,
ICAO_KUWAIT, ICAO_KYRGYZSTAN, ICAO_LAO_PDR, ICAO_LATVIA, ICAO_LEBANON,
ICAO_LESOTHO, ICAO_LIBERIA, ICAO_LIBYA, ICAO_LITHUANIA, ICAO_LUXEMBOURG,
ICAO_MADAGASCAR, ICAO_MALAWI, ICAO_MALAYSIA, ICAO_MALDIVES, ICAO_MALI,
ICAO_MALTA, ICAO_MARSHALL_ISLANDS, ICAO_MAURITANIA, ICAO_MAURITIUS,
ICAO_MEXICO, ICAO_MICRONESIA, ICAO_MONACO, ICAO_MONGOLIA, ICAO_MOROCCO,
ICAO_MOZAMBIQUE, ICAO_MYANMAR, ICAO_NAMIBIA, ICAO_NAURU, ICAO_NEPAL,
ICAO_NETHERLANDS, ICAO_NEW_ZEALAND, ICAO_NICARAGUA, ICAO_NIGER, ICAO_NIGERIA,
ICAO_NORWAY, ICAO_OMAN, ICAO_PAKISTAN, ICAO_PALAU, ICAO_PANAMA,
ICAO_PAPUA_NEW_GUINEA, ICAO_PARAGUAY, ICAO_PERU, ICAO_PHILIPPINES, ICAO_POLAND,
ICAO_PORTUGAL, ICAO_QATAR, ICAO_SOUTH_KOREA, ICAO_MOLDOVA, ICAO_ROMANIA,
ICAO_RUSSIA, ICAO_RWANDA, ICAO_SAINT_LUCIA, ICAO_SAINT_VINCENT_GRENADINES,
ICAO_SAMOA, ICAO_SAN_MARINO, ICAO_SAO_TOME_PRINCIPE, ICAO_SAUDI_ARABIA,
ICAO_SENEGAL, ICAO_SEYCHELLES, ICAO_SIERRA_LEONE, ICAO_SINGAPORE,
ICAO_SLOVAKIA, ICAO_SLOVENIA, ICAO_SOLOMON_ISLANDS, ICAO_SOMALIA,
ICAO_SOUTH_AFRICA, ICAO_SPAIN, ICAO_SRI_LANKA, ICAO_SUDAN, ICAO_SURINAME,
ICAO_SWAZILAND, ICAO_SWEDEN, ICAO_SWITZERLAND, ICAO_SYRIA, ICAO_TAJIKISTAN,
ICAO_THAILAND, ICAO_MACEDONIA, ICAO_TOGO, ICAO_TONGA, ICAO_TRINIDAD_TOBAGO,
ICAO_TUNISIA, ICAO_TURKEY, ICAO_TURKMENISTAN, ICAO_UGANDA, ICAO_UKRAINE,
ICAO_UAE, ICAO_UNITED_KINGDOM, ICAO_TANZANIA, ICAO_UNITED_STATES, ICAO_URUGUAY,
ICAO_UZBEKISTAN, ICAO_VANUATU, ICAO_VENEZUELA, ICAO_VIET_NAM, ICAO_YEMEN,
ICAO_ZAMBIA, ICAO_ZIMBABWE, ICAO_YUGOSLAVIA, ICAO_COUNTRY_CODE_END, ICAO_COUNTRY_CODE_ERROR
};


const unsigned int ICAO_ADDRESS_SIZE = 24;   //Number of address bits
struct ICAOAddressPrefix
{
    ICAO_Country country;
    const char *name;
    int prefix_size;  //In bits
    unsigned int prefix;
};



extern ICAOAddressPrefix icao_codes[];



#endif

